'use client'
import GeneralStats from "@components/molecules/mediaKitBlocks/GeneralStats"
import FollowerCount from "@components/molecules/mediaKitBlocks/FollowerCount"
import GenderDistribution from "../mediaKitBlocks/GenderDistribution"
import AgeDistribution from "../mediaKitBlocks/AgeDistribution"
import BrandCollaboration from "../mediaKitBlocks/BrandCollaboration"
import LocationDistribution from "../mediaKitBlocks/LocationDistribution"
import InstaRateCard from "../mediaKitBlocks/InstaRateCard"
import { useState } from "react"
import GeneratedByDodo from "public/images/generatedByDodo.png"
import Image from "next/image"

const MediaKitBlocks = ({ mediaKitDetails, setUpdateMediaKit }: { mediaKitDetails: any, setUpdateMediaKit: (updateMediaKit: boolean) => void }) => {
    
    return (
        <div className="flex flex-col gap-1 w-full pb-4">
            <div className="flex flex-col gap-1">
                <FollowerCount followerCount={mediaKitDetails?.followers} />
                <GeneralStats mode='edit' instaId={mediaKitDetails?.instaId} contentAnalytics={mediaKitDetails?.contentAnalytics}/>
            </div>

            <GenderDistribution
                genderAnalytics={mediaKitDetails?.genderAnalytics}
                instaId={mediaKitDetails?.instaId}
                setUpdateMediaKit={setUpdateMediaKit}
                mode="edit"
            />
            <BrandCollaboration
                brandData={mediaKitDetails?.brandCollabs}
                instaId={mediaKitDetails?.instaId}
                setUpdateMediaKit={setUpdateMediaKit}
                mode="edit"
            />
            <AgeDistribution
                ageDistributionData={mediaKitDetails?.ageAnalytics}
                instaId={mediaKitDetails?.instaId}
                setUpdateMediaKit={setUpdateMediaKit}
                mode="edit"
            />
            <LocationDistribution
                locationDistributionData={mediaKitDetails?.locationAnalytics}
                instaId={mediaKitDetails?.instaId}
                setUpdateMediaKit={setUpdateMediaKit}
                mode="edit"
            />
            <InstaRateCard
                rateCardData={mediaKitDetails?.rateCard}
                instaId={mediaKitDetails?.instaId}
                setUpdateMediaKit={setUpdateMediaKit}
                engagementRate={mediaKitDetails?.engagementRate}
                followers={mediaKitDetails?.followers}
                mode="edit"
                showDisclaimer={true}
            />

            <div className="flex justify-center items-center mt-8">
                <Image src={GeneratedByDodo} alt="Generated by Dodo" />
            </div>
        </div>      
    )
}

export default MediaKitBlocks