stages:
  - runner_up
  - build
  - deploy_dev
  - cleanup
  - runner_down

variables:
  AWS_DEFAULT_REGION: 'ap-south-1' # mumbai region for AWS
  IMAGE_TAG: 'dev-backend'

# cache node modules for faster builds
cache:
  paths:
    - node_modules/
  
# start the runner for image building foundation
start_ec2:
  stage: runner_up
  image: python:3.9
  script:
    - pip install boto3
    - python -c "import boto3; boto3.client('sts').get_caller_identity()"
    - python start_ec2.py

# Build the image for the application and push to dockerhub
build-application:
  stage: build
  tags:
    - dodo-group-runner
  before_script:
    - unset DOCKER_HOST
    - docker login $GITLAB_REGISTRY -u $GITLAB_USERNAME -p $REGISTRY_PASSWORD
  script:
    - git checkout feat/refactor
    - docker build -t registry.gitlab.com/dodo1604703/dodofe/feat/refactor .
    - docker images
    - docker push registry.gitlab.com/dodo1604703/dodofe/feat/refactor

# stop existing containers with {latest-1} code structure
stop_existing_infra:
  stage: deploy_dev
  tags:
    - dodo-group-runner
  # allow job to fail as there might be case that there is no container running, so we proceed with deployment
  allow_failure: true
  script: 
    - echo "$SSH_PRIVATE_KEY" > dodokey.pem
    - chmod 600 dodokey.pem
    - ssh -o StrictHostKeyChecking=no -i dodokey.pem ubuntu@ec2-13-127-180-62.ap-south-1.compute.amazonaws.com "sudo docker ps && sudo docker rm -f \$(sudo docker stop \$(sudo docker ps -a -q))"
  artifacts:
    paths:
      - dodokey.pem
    expire_in: 1 day

# spin up the latest code structure application
start_new_infra:
  stage: deploy_dev
  tags: 
    - dodo-group-runner
  script:
    - echo "$SSH_PRIVATE_KEY" > dodokey.pem
    - chmod 600 dodokey.pem
    - ssh -o StrictHostKeyChecking=no -i dodokey.pem ubuntu@ec2-13-127-180-62.ap-south-1.compute.amazonaws.com "sudo docker rmi -f \$(sudo docker images -aq) && sudo docker pull registry.gitlab.com/dodo1604703/dodofe/feat/refactor:latest && sudo docker images && sudo docker run -d -p 3000:3000 --restart=always registry.gitlab.com/dodo1604703/dodofe/feat/refactor:latest"

# remove image older than 48h from runner
deprecated_image:
  stage: cleanup
  tags: 
    - dodo-group-runner
  script:
    - docker image prune -a --filter "until=48h" -f
#   - docker rmi -f $(docker images "registry.gitlab.com/dodo1604703/dodofe/feat/refactor:*" -q | grep -v $(docker images "registry.gitlab.com/dodo1604703/dodofe/feat/refactor:latest" -q))
    - docker images registry.gitlab.com/dodo1604703/dodofe/feat/refactor --format '{{.ID}} {{.Tag}}' | grep -v ' latest$' | awk '{print $1}' | xargs -r docker rmi -f || true
    - echo "Updated list of image in RUNNER instance"
    - docker images

# stop the runner after deployment
stop_ec2:
  stage: runner_down
  image: python:3.9
  script:
    - pip install boto3
    - python stop_ec2.py