"use client";
import Head from 'next/head';
import Hero from './Hero';
import Features from './Features';
import Footer from './Footer';

export default function Home() {
    return (
        <div
            className="snap-y snap-mandatory h-screen overflow-scroll"
            style={{ backgroundImage: "url('/assets/landingBg.png')", backgroundSize: 'cover', backgroundPosition: 'center' }}
        >
            <Head>
                <title>My Landing Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Hero />
                <Features />
            </main>

            <Footer />
        </div>
    );
}