import { Metadata } from 'next'
import PreviewInvoice from './PreviewInvoice'

export async function generateMetadata({ params }: { params: { invoiceId: string } }): Promise<Metadata> {
  const { invoiceId } = params

  return {
    title: `Invoice #${invoiceId} | Dodo`,
    openGraph: {
      title: `Invoice #${invoiceId} | Dodo`,
      description: `Invoice #${invoiceId} generated by Dodo!`,
      url: `https://dodoclub.in/invoice/${invoiceId}`,
      // The image must be absolute, not relative:
      images: [
        'https://dodo-profile-audio.s3.ap-south-1.amazonaws.com/block-images/1744810417694-invoice.png',
      ],
    },
    twitter: {
      card: 'summary_large_image',
    },
  }
}

export default function InvoicePage({ params }: { params: { invoiceId: string } }) {
  return <PreviewInvoice invoiceId={params.invoiceId} />
}
