export default {
    slash: '/',
    sendOtp: '/send-otp',
    registerUser: '/auth/register',
    completeProfile: '/auth/complete-profile',
    getUserDetails: '/auth/user',
    updateUserDetails: '/update-user-details',
    createUserBlocks: '/create-block',
    getUserBlocks: '/user-blocks',
    createLink: '/create-links',
    reorderLink: '/reorder-links',
    getLinks: '/block-links',
    getLinkDetail: '/link',
    editLink: '/link/edit',
    archiveLink: '/link/archive',
    deleteLink: '/link/delete',
    publishData: '/publish',
    createRecipient : '/recipient/create',
    createClient : '/client/create',
    addBankDetails: '/bankDetails/add',
    createInvoice: '/invoice/create',
    getInvoceById: '/invoice/getInvoice',
    getAllInvoices: '/invoice/getAllInvoices',
    getInvoiceStats : '/invoice/getInvoiceStats',
    addSubHeading : '/invoice/addSubHeading'
}